# Quantitative Methods Overview

Biology, including ecology and conservation, is becoming increasingly quantitative. Familiarity with a range of statistical tools (frequentist, multivariate, Bayesian) is expected. Many researchers draw on quantitative methods; whether it is process or mathematical modelling, programming, bioinformatics, or bioeconomic analyses. We will only touch on key concepts in quantitative methods; in-depth training would require multiple full-semester courses. Here, we will carry out a few simple exercise that mimics some of the quantitative skills that you need to be a successful ecologist. These are:

1.	Use R!
2.	Manage data sets
3.	Plot data
4.	Fit a model to data

In this module there will be a small assignment with each of the above objectives. These are detailed below along with the percentage of your final grade that this is worth (the entire module is worth 10% of your final mark).


##What to hand in (as a single PDF file please!)

1. Written review of the first year guide. How useful was it to help you work through this module?

2. A short document that answers all the questions posed throughout this assignment (they are in italics)

3. Copies of the final version of all plots created (remember you can export these as image files which you can then paste in Word). Convert the Word document to a PDF file and upload it to the Dropbox folder in Brightspace. 

